Build package v2.0.0
effy-tech/active_admin-sortable_tree pull request #1
Opened 2021-06-10 14:48 UTC by fabien-qe

- Update build infos
- Add gem package build info in Readme

2021-06-17 09:10 UTC, ldlgds2 requested changes

2021-06-17 09:10 UTC, ldlgds2 commented on active_admin-sortable_tree.gemspec
> +  s.add_dependency('activeadmin', '~> 1.1')
Sinon ça casse suite à la mise à jour par Alexandre d'ActiveAdmin à 2.7 ...
```suggestion
  s.add_dependency('activeadmin', '>= 1.1')
```

2021-06-17 10:33 UTC, fabien-qe commented on active_admin-sortable_tree.gemspec
> +  s.add_dependency('activeadmin', '~> 1.1')
heu... ok sur le principe, pas trop fan du '>=', mais je veux pas n'importe quel version sup a 1.1... c'est pas safe. 😉

2021-06-17 10:35 UTC, fabien-qe commented on active_admin-sortable_tree.gemspec
> +  s.add_dependency('activeadmin', '~> 1.1')
J'aurais bien fait une autre PR du coup car celle ci cherche a mep la v 0.0.6. si on update les requirements, il faudrais bump la version de la gem et du package... a mon avis.

2021-06-17 10:35 UTC, ldlgds2 commented on active_admin-sortable_tree.gemspec
> +  s.add_dependency('activeadmin', '~> 1.1')
Ben dans ce cas on fait 
```suggestion
  s.add_dependency('activeadmin', '~> 2.7')
```

2021-06-17 10:43 UTC, ldlgds2 commented on active_admin-sortable_tree.gemspec
> +  s.add_dependency('activeadmin', '~> 1.1')
> J'aurais bien fait une autre PR du coup car celle ci cherche a mep la v 2.0.0. si on update les requirements, il faudrais bump la version de la gem et du package... a mon avis.

OK.

2021-06-17 13:10 UTC, ldlgds2 approved these changes

2021-07-26 09:19 UTC, diopmayacine approved these changes

2021-07-26 09:20 UTC, AlexQe approved these changes

2021-07-26 09:21 UTC, merged